export const learningPaths = [
    {
      id: 1,
      title: "HTML",
      level: "Beginner",
      description: "Start your web development journey with HTML.",
      slug: "html",
      color: "amber",
    },
    {
      id: 2,
      title: "CSS",
      level: "Beginner",
      description: "Learn modern responsive CSS.",
      slug: "css",
      color: "blue",
    },
    {
      id: 3,
      title: "JavaScript",
      level: "Intermediate",
      description: "Master modern JavaScript from scratch.",
      slug: "javascript",
      color: "yellow",
    },
    {
      id: 4,
      title: "React",
      level: "Intermediate",
      description: "Build modern React applications.",
      slug: "react",
      color: "cyan",
    },
    {
      id: 5,
      title: "Next.js",
      level: "Advanced",
      description: "Production-ready full-stack React.",
      slug: "nextjs",
      color: "purple",
    },
    {
      id: 6,
      title: "Node.js",
      level: "Intermediate",
      description: "Backend development using Node.js.",
      slug: "nodejs",
      color: "green",
    },
  ];